# Generated by Django 3.1.1 on 2020-10-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Mahasiswa', models.CharField(max_length=50)),
                ('Choose_File', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_dosen', models.CharField(max_length=45)),
                ('nama_dosen', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='DosenPengampu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahunAjaran', models.CharField(max_length=45)),
                ('dosen_Pengampu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRApps.dosen')),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=12)),
                ('nama_mahasiswa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodeMK', models.CharField(max_length=10)),
                ('namaMK', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosen_pengampu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRApps.dosenpengampu')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRApps.mahasiswa')),
            ],
        ),
        migrations.AddField(
            model_name='dosenpengampu',
            name='mata_kuliah',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRApps.matakuliah'),
        ),
    ]
