# Generated by Django 3.1.1 on 2020-10-06 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRApps', '0004_auto_20201006_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='KunciJawaban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=45)),
                ('point', models.IntegerField()),
                ('tanggalUjian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRApps.test')),
            ],
        ),
    ]
