# Generated by Django 3.1.1 on 2020-10-06 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRApps', '0005_kuncijawaban'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuncijawaban',
            name='mata_kuliah',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TRApps.dosenpengampu'),
            preserve_default=False,
        ),
    ]
