# Generated by Django 3.1.2 on 2020-10-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TRApps', '0007_auto_20201007_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images/')),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AssessmentAns',
        ),
        migrations.AlterField(
            model_name='scoring',
            name='tanggalUjian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TRApps.test'),
        ),
    ]
