# Generated by Django 3.1.2 on 2020-10-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TRApps', '0008_auto_20201024_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
